#include "native_mesh.hpp"

#include <algorithm>
#include <array>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

// WebGL 2 mesh, sky-map, and space-dust implementation selected for the Wasm
// target. The public Doof API remains the shared std/game API; the historic
// metal*Handle method names are ABI slots and carry opaque WebGL 2 resource IDs.
#if defined(__EMSCRIPTEN__)
extern "C" {
__attribute__((import_module("doof_game"), import_name("mesh_create")))
int32_t doof_game_mesh_create(int32_t window, const double* vertices, int32_t vertex_values,
    const uint32_t* indices, int32_t index_count);
__attribute__((import_module("doof_game"), import_name("batch_create")))
int32_t doof_game_batch_create(int32_t window, int32_t capacity);
__attribute__((import_module("doof_game"), import_name("batch_set_instance")))
void doof_game_batch_set_instance(
    int32_t window, int32_t batch, int32_t slot, const float* values, int32_t value_count);
__attribute__((import_module("doof_game"), import_name("dust_create")))
int32_t doof_game_dust_create(int32_t window, const double* particles, int32_t particle_values);
__attribute__((import_module("doof_game"), import_name("shader_buffer_create")))
int32_t doof_game_shader_buffer_create(int32_t window, const uint8_t* data, int32_t byte_count);
__attribute__((import_module("doof_game"), import_name("shader_pipeline_create")))
int32_t doof_game_shader_pipeline_create(
    int32_t window, const char* vertex_source, const char* fragment_source,
    const int32_t* attribute_indices, const int32_t* attribute_buffers,
    const int32_t* attribute_offsets, const int32_t* attribute_formats, int32_t attribute_count,
    const int32_t* layout_buffers, const int32_t* layout_strides,
    const int32_t* layout_step_functions, const int32_t* layout_step_rates, int32_t layout_count);
__attribute__((import_module("doof_game"), import_name("shader_draw")))
int32_t doof_game_shader_draw(
    int32_t window, int32_t pipeline,
    const int32_t* vertex_buffer_indices, const int32_t* vertex_buffer_handles,
    const int32_t* vertex_buffer_offsets, int32_t vertex_buffer_count,
    int32_t index_buffer, int32_t index_count, int32_t vertex_count, int32_t instance_count);
__attribute__((import_module("doof_game"), import_name("resource_delete")))
void doof_game_resource_delete(int32_t window, int32_t kind, int32_t resource);
__attribute__((import_module("doof_game"), import_name("draw_mesh")))
void doof_game_draw_mesh(int32_t window, int32_t mesh, int32_t texture, int32_t textured,
    int32_t blend_mode, const double* view_projection, const double* model, const double* normal,
    double ambient, double directional, double light_x, double light_y, double light_z,
    double red, double green, double blue, double alpha);
__attribute__((import_module("doof_game"), import_name("draw_batch")))
void doof_game_draw_batch(
    int32_t window, int32_t mesh, int32_t batch, int32_t texture, int32_t textured,
    int32_t blend_mode, int32_t instance_count, const double* view_projection,
    double ambient, double directional, double light_x, double light_y, double light_z,
    double eye_x, double eye_y, double eye_z);
__attribute__((import_module("doof_game"), import_name("draw_sky")))
void doof_game_draw_sky(int32_t window, int32_t texture, int32_t pixel_width, int32_t pixel_height,
    double fov_y, double exposure, const double* rotation);
__attribute__((import_module("doof_game"), import_name("draw_dust")))
void doof_game_draw_dust(int32_t window, int32_t dust, int32_t particle_count, int32_t pixel_height,
    double camera_x, double camera_y, double camera_z, double field_size, double particle_size,
    double fade_start, double fade_end, double opacity, double red, double green, double blue,
    const double* camera_matrix);
}
#endif

namespace doof_game {
namespace {

struct VertexValues { std::vector<double> values; std::vector<uint32_t> indices; };
void matrix4(double* out,double m00,double m01,double m02,double m03,double m10,double m11,double m12,double m13,double m20,double m21,double m22,double m23,double m30,double m31,double m32,double m33){double values[16]={m00,m01,m02,m03,m10,m11,m12,m13,m20,m21,m22,m23,m30,m31,m32,m33};for(int i=0;i<16;++i)out[i]=values[i];}
void matrix3(double* out,double m00,double m01,double m02,double m10,double m11,double m12,double m20,double m21,double m22){double values[9]={m00,m01,m02,m10,m11,m12,m20,m21,m22};for(int i=0;i<9;++i)out[i]=values[i];}

}  // namespace

struct NativeSimpleMesh::Impl{int32_t window=0,resource=0,vertexCount=0,indexCount=0;Impl(int32_t w,int32_t r,int32_t vc,int32_t ic):window(w),resource(r),vertexCount(vc),indexCount(ic){}};
NativeSimpleMesh::NativeSimpleMesh(void* device,void* vertexBuffer,void*,int32_t vertexCount,int32_t indexCount):impl_(std::make_shared<Impl>(static_cast<int32_t>(reinterpret_cast<std::uintptr_t>(device)),static_cast<int32_t>(reinterpret_cast<std::uintptr_t>(vertexBuffer)),vertexCount,indexCount)){}NativeSimpleMesh::~NativeSimpleMesh(){if(impl_.use_count()==1&&impl_->resource)doof_game_resource_delete(impl_->window,0,impl_->resource);}int32_t NativeSimpleMesh::vertexCount()const{return impl_->vertexCount;}int32_t NativeSimpleMesh::indexCount()const{return impl_->indexCount;}int64_t NativeSimpleMesh::metalDeviceHandle()const{return impl_->window;}int64_t NativeSimpleMesh::metalVertexBufferHandle()const{return impl_->resource;}int64_t NativeSimpleMesh::metalIndexBufferHandle()const{return impl_->resource;}
struct NativeSimpleMeshBuilder::Impl{VertexValues data;};std::shared_ptr<NativeSimpleMeshBuilder> NativeSimpleMeshBuilder::create(){return std::make_shared<NativeSimpleMeshBuilder>();}NativeSimpleMeshBuilder::NativeSimpleMeshBuilder():impl_(std::make_shared<Impl>()){}NativeSimpleMeshBuilder::~NativeSimpleMeshBuilder()=default;
int32_t NativeSimpleMeshBuilder::addVertex(double x,double y,double z,double red,double green,double blue,double alpha,double u,double v,double nx,double ny,double nz){auto& values=impl_->data.values;values.insert(values.end(),{x,y,z,red,green,blue,alpha,u,v,nx,ny,nz});return static_cast<int32_t>(values.size()/12-1);}std::shared_ptr<NativeSimpleMeshBuilder> NativeSimpleMeshBuilder::addTriangle(int32_t a,int32_t b,int32_t c){impl_->data.indices.push_back(static_cast<uint32_t>(a));impl_->data.indices.push_back(static_cast<uint32_t>(b));impl_->data.indices.push_back(static_cast<uint32_t>(c));return shared_from_this();}
doof::Result<std::shared_ptr<NativeSimpleMesh>,std::string> NativeSimpleMeshBuilder::build(int64_t window){if(impl_->data.values.empty())return doof::Failure<std::string>{"Simple mesh has no vertices"};if(impl_->data.indices.empty())return doof::Failure<std::string>{"Simple mesh has no triangles"};const std::size_t vertexCount=impl_->data.values.size()/12;for(uint32_t index:impl_->data.indices)if(index>=vertexCount)return doof::Failure<std::string>{"Simple mesh triangle index is out of range"};int32_t resource=doof_game_mesh_create(window,impl_->data.values.data(),impl_->data.values.size(),impl_->data.indices.data(),impl_->data.indices.size());if(!resource)return doof::Failure<std::string>{"Failed to create WebGL 2 mesh"};return doof::Success<std::shared_ptr<NativeSimpleMesh>>{std::make_shared<NativeSimpleMesh>(reinterpret_cast<void*>(static_cast<std::uintptr_t>(window)),reinterpret_cast<void*>(static_cast<std::uintptr_t>(resource)),nullptr,impl_->data.values.size()/12,impl_->data.indices.size())};}

struct NativeSimpleModelBatch::Impl{int32_t window=0,resource=0,capacity=0,count=0;Impl(int32_t w,int32_t r,int32_t c):window(w),resource(r),capacity(c){}};
doof::Result<std::shared_ptr<NativeSimpleModelBatch>,std::string> NativeSimpleModelBatch::create(int64_t window,int32_t capacity){if(!window)return doof::Failure<std::string>{"WebGL 2 game surface handle is invalid"};if(capacity<=0)return doof::Failure<std::string>{"Simple model batch capacity must be positive"};int32_t resource=doof_game_batch_create(window,capacity);if(!resource)return doof::Failure<std::string>{"Failed to create WebGL 2 model batch instance buffer"};return doof::Success<std::shared_ptr<NativeSimpleModelBatch>>{std::make_shared<NativeSimpleModelBatch>(reinterpret_cast<void*>(static_cast<std::uintptr_t>(window)),reinterpret_cast<void*>(static_cast<std::uintptr_t>(resource)),capacity)};}
NativeSimpleModelBatch::NativeSimpleModelBatch(void* device,void* instanceBuffer,int32_t capacity):impl_(std::make_shared<Impl>(static_cast<int32_t>(reinterpret_cast<std::uintptr_t>(device)),static_cast<int32_t>(reinterpret_cast<std::uintptr_t>(instanceBuffer)),capacity)){}
NativeSimpleModelBatch::~NativeSimpleModelBatch(){if(impl_.use_count()==1&&impl_->resource)doof_game_resource_delete(impl_->window,2,impl_->resource);}
int32_t NativeSimpleModelBatch::capacity()const{return impl_->capacity;}int32_t NativeSimpleModelBatch::count()const{return impl_->count;}void NativeSimpleModelBatch::setCount(int32_t count){impl_->count=std::clamp(count,0,impl_->capacity);}
void NativeSimpleModelBatch::setInstance(int32_t slot,double m00,double m01,double m02,double m03,double m10,double m11,double m12,double m13,double m20,double m21,double m22,double m23,double m30,double m31,double m32,double m33,double n00,double n01,double n02,double n10,double n11,double n12,double n20,double n21,double n22,double red,double green,double blue,double alpha,double whiteBlend,double uvOffsetX,double uvOffsetY,double uvScaleX,double uvScaleY,double specular,double shininess,double fresnel,double fresnelPower){if(slot<0||slot>=impl_->capacity)return;std::array<float,44> values={float(m00),float(m01),float(m02),float(m03),float(m10),float(m11),float(m12),float(m13),float(m20),float(m21),float(m22),float(m23),float(m30),float(m31),float(m32),float(m33),float(n00),float(n01),float(n02),0.0f,float(n10),float(n11),float(n12),0.0f,float(n20),float(n21),float(n22),0.0f,float(red),float(green),float(blue),float(alpha),float(whiteBlend),float(specular),float(shininess),float(fresnel),float(uvOffsetX),float(uvOffsetY),float(uvScaleX),float(uvScaleY),float(fresnelPower),0.0f,0.0f,0.0f};doof_game_batch_set_instance(impl_->window,impl_->resource,slot,values.data(),values.size());}
int64_t NativeSimpleModelBatch::metalInstanceBufferHandle()const{return impl_->resource;}

struct NativeSpaceDust::Impl{int32_t window=0,resource=0,count=0;Impl(int32_t w,int32_t r,int32_t c):window(w),resource(r),count(c){}};NativeSpaceDust::NativeSpaceDust(void* device,void* buffer,int32_t count):impl_(std::make_shared<Impl>(static_cast<int32_t>(reinterpret_cast<std::uintptr_t>(device)),static_cast<int32_t>(reinterpret_cast<std::uintptr_t>(buffer)),count)){}NativeSpaceDust::~NativeSpaceDust(){if(impl_.use_count()==1&&impl_->resource)doof_game_resource_delete(impl_->window,1,impl_->resource);}int32_t NativeSpaceDust::particleCount()const{return impl_->count;}int64_t NativeSpaceDust::metalDeviceHandle()const{return impl_->window;}int64_t NativeSpaceDust::metalParticleBufferHandle()const{return impl_->resource;}
struct NativeSpaceDustBuilder::Impl{std::vector<double> values;};std::shared_ptr<NativeSpaceDustBuilder> NativeSpaceDustBuilder::create(){return std::make_shared<NativeSpaceDustBuilder>();}NativeSpaceDustBuilder::NativeSpaceDustBuilder():impl_(std::make_shared<Impl>()){}NativeSpaceDustBuilder::~NativeSpaceDustBuilder()=default;std::shared_ptr<NativeSpaceDustBuilder> NativeSpaceDustBuilder::addParticle(double x,double y,double z,double brightness){impl_->values.insert(impl_->values.end(),{x,y,z,brightness});return shared_from_this();}doof::Result<std::shared_ptr<NativeSpaceDust>,std::string> NativeSpaceDustBuilder::build(int64_t window){if(impl_->values.empty())return doof::Failure<std::string>{"Space dust has no particles"};int32_t resource=doof_game_dust_create(window,impl_->values.data(),impl_->values.size());if(!resource)return doof::Failure<std::string>{"Failed to create WebGL dust"};return doof::Success<std::shared_ptr<NativeSpaceDust>>{std::make_shared<NativeSpaceDust>(reinterpret_cast<void*>(static_cast<std::uintptr_t>(window)),reinterpret_cast<void*>(static_cast<std::uintptr_t>(resource)),impl_->values.size()/4)};}

struct NativeShaderBuffer::Impl{int32_t window=0,resource=0,byteLength=0;Impl(int32_t w,int32_t r,int32_t size):window(w),resource(r),byteLength(size){}};
doof::Result<std::shared_ptr<NativeShaderBuffer>,std::string> NativeShaderBuffer::create(int64_t windowHandle,const std::shared_ptr<std::vector<uint8_t>>& data){if(!data||data->empty())return doof::Failure<std::string>{"Shader buffer data is empty"};int32_t window=static_cast<int32_t>(windowHandle);int32_t resource=doof_game_shader_buffer_create(window,data->data(),static_cast<int32_t>(data->size()));if(!resource)return doof::Failure<std::string>{"Failed to create WebGL 2 shader buffer"};return doof::Success<std::shared_ptr<NativeShaderBuffer>>{std::make_shared<NativeShaderBuffer>(reinterpret_cast<void*>(static_cast<std::uintptr_t>(window)),reinterpret_cast<void*>(static_cast<std::uintptr_t>(resource)),static_cast<int32_t>(data->size()))};}
NativeShaderBuffer::NativeShaderBuffer(void* window,void* resource,int32_t byteLength):impl_(std::make_shared<Impl>(static_cast<int32_t>(reinterpret_cast<std::uintptr_t>(window)),static_cast<int32_t>(reinterpret_cast<std::uintptr_t>(resource)),byteLength)){}NativeShaderBuffer::~NativeShaderBuffer(){if(impl_.use_count()==1&&impl_->resource)doof_game_resource_delete(impl_->window,3,impl_->resource);}int32_t NativeShaderBuffer::byteLength()const{return impl_->byteLength;}int64_t NativeShaderBuffer::metalBufferHandle()const{return impl_->resource;}

struct NativeShaderPipeline::Impl{int32_t window=0,resource=0;Impl(int32_t w,int32_t r):window(w),resource(r){}};
doof::Result<std::shared_ptr<NativeShaderPipeline>,std::string> NativeShaderPipeline::create(int64_t windowHandle,const std::string& vertexSource,const std::string& fragmentSource,const std::string& vertexFunction,const std::string& fragmentFunction,const std::shared_ptr<std::vector<int32_t>>& attributeIndices,const std::shared_ptr<std::vector<int32_t>>& attributeBuffers,const std::shared_ptr<std::vector<int32_t>>& attributeOffsets,const std::shared_ptr<std::vector<int32_t>>& attributeFormats,const std::shared_ptr<std::vector<int32_t>>& layoutBuffers,const std::shared_ptr<std::vector<int32_t>>& layoutStrides,const std::shared_ptr<std::vector<int32_t>>& layoutStepFunctions,const std::shared_ptr<std::vector<int32_t>>& layoutStepRates){if(vertexFunction!="main"||fragmentFunction!="main")return doof::Failure<std::string>{"WebGL 2 shader entry points must be named main"};if(!attributeIndices||!attributeBuffers||!attributeOffsets||!attributeFormats||!layoutBuffers||!layoutStrides||!layoutStepFunctions||!layoutStepRates)return doof::Failure<std::string>{"WebGL 2 shader descriptors are invalid"};int32_t window=static_cast<int32_t>(windowHandle);int32_t resource=doof_game_shader_pipeline_create(window,vertexSource.c_str(),fragmentSource.c_str(),attributeIndices->data(),attributeBuffers->data(),attributeOffsets->data(),attributeFormats->data(),static_cast<int32_t>(attributeIndices->size()),layoutBuffers->data(),layoutStrides->data(),layoutStepFunctions->data(),layoutStepRates->data(),static_cast<int32_t>(layoutBuffers->size()));if(!resource)return doof::Failure<std::string>{"Failed to compile or link WebGL 2 shader program"};return doof::Success<std::shared_ptr<NativeShaderPipeline>>{std::make_shared<NativeShaderPipeline>(reinterpret_cast<void*>(static_cast<std::uintptr_t>(window)),reinterpret_cast<void*>(static_cast<std::uintptr_t>(resource)),nullptr,nullptr,vertexFunction,fragmentFunction)};}
NativeShaderPipeline::NativeShaderPipeline(void* window,void* resource,void*,void*,std::string,std::string):impl_(std::make_shared<Impl>(static_cast<int32_t>(reinterpret_cast<std::uintptr_t>(window)),static_cast<int32_t>(reinterpret_cast<std::uintptr_t>(resource)))){}NativeShaderPipeline::~NativeShaderPipeline(){if(impl_.use_count()==1&&impl_->resource)doof_game_resource_delete(impl_->window,4,impl_->resource);}doof::Result<int64_t,std::string> NativeShaderPipeline::metalPipelineHandle(int32_t,bool,bool){if(!impl_->resource)return doof::Failure<std::string>{"WebGL 2 shader pipeline is invalid"};return doof::Success<int64_t>{impl_->resource};}

#define MESH_ARGS double m00,double m01,double m02,double m03,double m10,double m11,double m12,double m13,double m20,double m21,double m22,double m23,double m30,double m31,double m32,double m33,double modelM00,double modelM01,double modelM02,double modelM03,double modelM10,double modelM11,double modelM12,double modelM13,double modelM20,double modelM21,double modelM22,double modelM23,double modelM30,double modelM31,double modelM32,double modelM33,double n00,double n01,double n02,double n10,double n11,double n12,double n20,double n21,double n22,double ambient,double directional,double lightX,double lightY,double lightZ,double,double,double,double red,double green,double blue,double alpha,double,double,double,double,double,double,double,double,double
void drawNativeSimpleMesh(std::shared_ptr<NativeSimpleMesh> mesh,int64_t window,int64_t,int32_t blend,bool,bool,MESH_ARGS){double view[16],model[16],normal[9];matrix4(view,m00,m01,m02,m03,m10,m11,m12,m13,m20,m21,m22,m23,m30,m31,m32,m33);matrix4(model,modelM00,modelM01,modelM02,modelM03,modelM10,modelM11,modelM12,modelM13,modelM20,modelM21,modelM22,modelM23,modelM30,modelM31,modelM32,modelM33);matrix3(normal,n00,n01,n02,n10,n11,n12,n20,n21,n22);doof_game_draw_mesh(window,mesh->metalVertexBufferHandle(),0,0,blend,view,model,normal,ambient,directional,lightX,lightY,lightZ,red,green,blue,alpha);}
void drawNativeTexturedSimpleMesh(std::shared_ptr<NativeSimpleMesh> mesh,int64_t texture,int64_t window,int64_t,int32_t blend,bool,bool,MESH_ARGS){double view[16],model[16],normal[9];matrix4(view,m00,m01,m02,m03,m10,m11,m12,m13,m20,m21,m22,m23,m30,m31,m32,m33);matrix4(model,modelM00,modelM01,modelM02,modelM03,modelM10,modelM11,modelM12,modelM13,modelM20,modelM21,modelM22,modelM23,modelM30,modelM31,modelM32,modelM33);matrix3(normal,n00,n01,n02,n10,n11,n12,n20,n21,n22);doof_game_draw_mesh(window,mesh->metalVertexBufferHandle(),texture,1,blend,view,model,normal,ambient,directional,lightX,lightY,lightZ,red,green,blue,alpha);}
#undef MESH_ARGS

void drawNativeSimpleModelBatch(std::shared_ptr<NativeSimpleMesh> mesh,std::shared_ptr<NativeSimpleModelBatch> batch,int64_t texture,bool textured,int64_t window,int64_t,int32_t blend,bool,bool,double m00,double m01,double m02,double m03,double m10,double m11,double m12,double m13,double m20,double m21,double m22,double m23,double m30,double m31,double m32,double m33,double ambient,double directional,double lightX,double lightY,double lightZ,double eyeX,double eyeY,double eyeZ){if(!mesh||!batch||mesh->indexCount()<=0||batch->count()<=0)return;double view[16];matrix4(view,m00,m01,m02,m03,m10,m11,m12,m13,m20,m21,m22,m23,m30,m31,m32,m33);doof_game_draw_batch(window,mesh->metalVertexBufferHandle(),batch->metalInstanceBufferHandle(),texture,textured?1:0,blend,batch->count(),view,ambient,directional,lightX,lightY,lightZ,eyeX,eyeY,eyeZ);}

void drawNativeEquirectangularSkyMap(int64_t texture,int64_t window,int64_t,bool,int32_t width,int32_t height,double fovY,double exposure,double m00,double m01,double m02,double m10,double m11,double m12,double m20,double m21,double m22){double rotation[9];matrix3(rotation,m00,m01,m02,m10,m11,m12,m20,m21,m22);doof_game_draw_sky(window,texture,width,height,fovY,exposure,rotation);}
void drawNativeSpaceDust(std::shared_ptr<NativeSpaceDust> dust,int64_t window,int64_t,bool,int32_t,int32_t height,double cameraX,double cameraY,double cameraZ,double fieldSize,double particleSize,double fadeStart,double fadeEnd,double opacity,double red,double green,double blue,double m00,double m01,double m02,double m03,double m10,double m11,double m12,double m13,double m20,double m21,double m22,double m23,double m30,double m31,double m32,double m33){double matrix[16];matrix4(matrix,m00,m01,m02,m03,m10,m11,m12,m13,m20,m21,m22,m23,m30,m31,m32,m33);doof_game_draw_dust(window,dust->metalParticleBufferHandle(),dust->particleCount(),height,cameraX,cameraY,cameraZ,fieldSize,particleSize,fadeStart,fadeEnd,opacity,red,green,blue,matrix);}

doof::Result<void,std::string> drawNativeShader(std::shared_ptr<NativeShaderPipeline> pipeline,const std::shared_ptr<std::vector<int32_t>>& vertexBufferIndices,const std::shared_ptr<std::vector<int64_t>>& vertexBufferHandles,const std::shared_ptr<std::vector<int32_t>>& vertexBufferOffsets,const std::shared_ptr<std::vector<int32_t>>& vertexBytesIndices,const std::shared_ptr<std::vector<int64_t>>& vertexBytesHandles,const std::shared_ptr<std::vector<int32_t>>& vertexBytesOffsets,const std::shared_ptr<std::vector<int32_t>>& fragmentBytesIndices,const std::shared_ptr<std::vector<int64_t>>& fragmentBytesHandles,const std::shared_ptr<std::vector<int32_t>>& fragmentBytesOffsets,const std::shared_ptr<std::vector<int32_t>>& fragmentTextureIndices,const std::shared_ptr<std::vector<int64_t>>& fragmentTextureHandles,int64_t indexBufferHandle,int32_t indexCount,int32_t vertexCount,int32_t instanceCount,int64_t windowHandle,int32_t blendMode,bool hasColorAttachment,bool hasDepthAttachment){(void)blendMode;(void)hasColorAttachment;(void)hasDepthAttachment;if(!vertexBytesIndices->empty()||!vertexBytesHandles->empty()||!vertexBytesOffsets->empty()||!fragmentBytesIndices->empty()||!fragmentBytesHandles->empty()||!fragmentBytesOffsets->empty())return doof::Failure<std::string>{"WebGL 2 custom shader uniform-byte bindings are not implemented"};if(!fragmentTextureIndices->empty()||!fragmentTextureHandles->empty())return doof::Failure<std::string>{"WebGL 2 custom shader texture bindings are not implemented"};std::vector<int32_t> handles;handles.reserve(vertexBufferHandles->size());for(int64_t handle:*vertexBufferHandles)handles.push_back(static_cast<int32_t>(handle));auto pipelineHandle=pipeline->metalPipelineHandle(0,true,false);if(doof::is_failure(pipelineHandle))return doof::Failure<std::string>{doof::failure_error(pipelineHandle)};int32_t ok=doof_game_shader_draw(static_cast<int32_t>(windowHandle),static_cast<int32_t>(doof::success_value(pipelineHandle)),vertexBufferIndices->data(),handles.data(),vertexBufferOffsets->data(),static_cast<int32_t>(handles.size()),static_cast<int32_t>(indexBufferHandle),indexCount,vertexCount,instanceCount);if(!ok)return doof::Failure<std::string>{"Failed to draw WebGL 2 custom shader"};return doof::Success<void>{};}

}  // namespace doof_game
